# Generated by Django 4.2.16 on 2024-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
