# Generated by Django 4.2.16 on 2024-11-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0002_libros_valoracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libros',
            options={'permissions': [('can_edit_clubes', 'Puede editar clubes')]},
        ),
    ]
