# Generated by Django 4.2.16 on 2024-11-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0003_alter_libros_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libros',
            options={'permissions': [('development', 'Desarrollador')]},
        ),
    ]
