# Generated by Django 4.2.16 on 2024-11-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_libros', '0005_alter_libros_options_libros_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='fecha_publicacion',
            new_name='fecha_modificacion',
        ),
    ]
